### PR TITLE
Fix intermittent LTE test.

### LINKED ISSUE #791: Intermittent test: ULModAccSingleCarrierFromExample_FetchData_DataLooksReasonable
Look into and fix intermittent test failure for `NiRFmxLTEDriverApiTests.ULModAccSingleCarrierFromExample_FetchData_DataLooksReasonable`

It's been popping up intermittently on PR builds for a while now.

[AB#2220010](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2220010)

### PR DESCRIPTION
**Pull request by reckenro**
### What does this Pull Request accomplish?

Fixes the intermittent LTE test by actually making a call that was missing.

### Why should this Pull Request be merged?

Fixes #791 

### What testing has been done?

Ran test in a loop for 500 times with `SetUp`/`TearDown` call at beginning/end of loop.
Without changes failed consistently within 100 iterations.
After change it's passed consistently.

### CODE REVIEW

File: source/tests/system/nirfmxlte_driver_api_tests.cpp [hunk 1]
```diff
@@ -1110,6 +1110,7 @@ TEST_F(NiRFmxLTEDriverApiTests, ULModAccSingleCarrierFromExample_FetchData_DataL
     EXPECT_SUCCESS(session, client::initiate(stub(), session, "", ""));
 
     // Intermittently gives "374603: Unable to synchronize." and outputs nan values
+    mod_acc_fetch_composite_evm_response = client::mod_acc_fetch_composite_evm(stub(), session, "", 10.0);
```
Comment (reckenro) [inline source/tests/system/nirfmxlte_driver_api_tests.cpp:1113]: Finally looked at this intermittent test and noticed we never actually called this method so the `mod_acc_fetch_composite_evm_response` was just the default and we weren't doing anything to prevent that `3374603: Unable to synchronize` error from showing up.

**Review by astarche — APPROVED** [review]
