### PR TITLE
codegen: Report DAQmx event registration failure by closing stream

### LINKED ISSUE #924: NI gRPC Device Server reports DAQmx event registration errors as events, not as errors
The NI gRPC Device Server uses server streaming to return a response for each event generated by DAQmx. However, when a DAQmx event registration function (like DAQmxRegisterDoneEvent) returns an error, the server reports the error by sending a streaming response where `response.status` is the error code.

When the rest of the NI gRPC Device Server APIs were updated to report errors by returning a gRPC status, the DAQmx event registration functions were not updated.

Implications:
- It is difficult for clients to synchronously detect whether event registration failed.
  - In the success case, no responses are generated until DAQmx notifies the server of an event, so waiting indefinitely for a response only works in the error case.
  - Waiting indefinitely for initial metadata does not guarantee that the error will be reported at the same time because the server sends initial metadata before reporting the error.
- Rich error descriptions are not reported for event registration errors, only an error code.
- For done events, a fatal `response.status` is ambiguous: it can mean that event registration failed or that the acquisition/generation encountered an error.
- The server does not close the stream when a event registration error occurs, but it will never send any responses other than the one containing the error code.

Addressing this is required to fix nidaqmx-python bug [AB#2395958](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2395958): "GrpcStubInterpreter does not report event registration errors to caller". nidaqmx-python reports event registration errors by raising an exception from the `register_done_event` method, not by invoking the event callback. We will have the same problem when supporting gRPC in other versions of the DAQmx API.

[AB#2396353](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2396353)

### PR DESCRIPTION
**Pull request by bkeryan**
### What does this Pull Request accomplish?

The NI gRPC Device Server uses server streaming to return a response for each
event generated by DAQmx. However, when a DAQmx event registration function
(like DAQmxRegisterDoneEvent) returns an error, the server reports the error by
sending a streaming response where `response.status` is the error code.

Implications:

- It is difficult for clients to synchronously detect whether event registration
  failed.
  - In the success case, no responses are generated until DAQmx notifies the
     server of an event, so waiting indefinitely for a response only works in the
     error case.
  - Waiting indefinitely for initial metadata does not guarantee that the error
     will be reported at the same time because the server sends initial metadata
     before reporting the error.
 - Rich error descriptions are not reported for event registration errors, only
   an error code.
 - For done events, a fatal `response.status` is ambiguous: it can mean that
   event registration failed or that the acquisition/generation encountered an
   error.
 - The server does not close the stream when a event registration error occurs,
   but it will never send any responses other than the one containing the error
   code.

Reporting event registration errors by closing the stream solves these problems:

- After the client waits for initial metadata, they can check whether the event
  stream is done/closed without any additional waiting.
- When an event registration error occurs, the event stream is closed with a
  gRPC status containing the rich error message and `ni-error` trailing metadata
  indicating the error code.
- The done event stream is only closed when an event registration error occurs,
  when either side cancels, or when gRPC closes it for another reason. It is not
  closed when the DAQmx acquisition/generation encounters an error.
- The server closes the stream, so clients know to stop reading events.

This is a breaking change. However, it only affects error cases, and clients
should already handle gRPC errors when reading the event stream.

### Why should this Pull Request be merged?

Fixes #924 

Prerequisite for fixing [AB#2395958](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2395958): GrpcStubInterpreter does not report event registration errors to caller

### What testing has been done?

Manually tested with updated Python examples, which will be in a separate PR.
Ran updated C++ tests with `SystemTestsRunner.exe --gtest_filter=*DAQmx*`

### CODE REVIEW

**Comment by bkeryan** [comment]
When the server returns a gRPC status before sending initial metadata, it sends what the [gRPC over HTTP2](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) specification calls a "Trailers-Only" response. `WaitForInitialMetadata` waits for HTTP2 headers and it gets HTTP2 trailers instead.

If something caused this not to work (implementation change, HTTP2 proxy, gRPC-Web proyx?), the error would still be reported to the client when the client's worker thread reads the event stream. However, the client's worker thread needs to have a way to report event stream errors anyway, because there many other reasons the stream could be closed besides event registration errors.

File: generated/nidaqmx/nidaqmx_service.cpp [hunk 1]
```diff
@@ -14001,15 +14001,15 @@ namespace nidaqmx_grpc {
     using CallbackRouter = nidevice_grpc::CallbackRouter<int32, TaskHandle, int32>;
     class RegisterDoneEventReactor : public nidevice_grpc::ServerWriterReactor<RegisterDoneEventResponse, nidevice_grpc::CallbackRegistration> {
     public:
-    RegisterDoneEventReactor(const RegisterDoneEventRequest& request, NiDAQmxLibraryInterface* library, const ResourceRepositorySharedPtr& session_repository)
+    RegisterDoneEventReactor(::grpc::CallbackServerContext* context, const RegisterDoneEventRequest* request, NiDAQmxLibraryInterface* library, NiDAQmxService* service)
```
Comment (bkeryan) [inline generated/nidaqmx/nidaqmx_service.cpp:14004]: Regarding service object lifetime:
- The library and service objects are managed with the same shared_ptr: https://github.com/ni/grpc-device/blob/main/generated/nidaqmx/nidaqmx_service_registrar.cpp . If the service object can be deleted out from under us, then so can the library object.
- The constructor and `start()` method are passed the resource repository shared_ptr by reference, not by value. The reference is to a member variable of the service class.

File: generated/nidaqmx/nidaqmx_service.cpp [hunk 2]
```diff
@@ -14001,15 +14001,15 @@ namespace nidaqmx_grpc {
...
     {
-      auto status = start(&request, library, session_repository);
+      auto status = start(context, request, library, service);
       if (!status.ok()) {
         this->Finish(status);
       }
```
Comment (bkeryan) [inline generated/nidaqmx/nidaqmx_service.cpp:14009]: This asserted while testing with nidaqmx-python:
image

```
 	win32u.dll!NtUserWaitMessage()	Unknown
 	user32.dll!DialogBox2()	Unknown
 	user32.dll!InternalDialogBox()	Unknown
 	user32.dll!SoftModalMessageBox()	Unknown
 	user32.dll!MessageBoxWorker(struct _MSGBOXDATA *)	Unknown
 	user32.dll!MessageBoxTimeoutW()	Unknown
 	user32.dll!MessageBoxW()	Unknown
 	ucrtbased.dll!__acrt_MessageBoxW(HWND__ * hwnd, const wchar_t * text, const wchar_t * caption, unsigned int type) Line 695	C++
 	ucrtbased.dll!__crt_char_traits<wchar_t>::message_box<HWND__ * __ptr64,wchar_t const * __ptr64 const & __ptr64,wchar_t const * __ptr64 const & __ptr64,unsigned int const & __ptr64>(HWND__ * && <args_0>, const wchar_t * const & <args_1>, const wchar_t * const & <args_2>, const unsigned int & <args_3>) Line 121	C++
 	ucrtbased.dll!common_show_message_box<wchar_t>(const wchar_t * const text, const wchar_t * const caption, const unsigned int type) Line 117	C++
 	ucrtbased.dll!__acrt_show_wide_message_box(const wchar_t * text, const wchar_t * caption, unsigned int type) Line 135	C++
 	ucrtbased.dll!common_message_window<wchar_t>(const int report_type, void * const return_address, const wchar_t * const file_name, const wchar_t * const line_number, const wchar_t * const module_name, const wchar_t * const user_message) Line 404	C++
 	ucrtbased.dll!__acrt_MessageWindowW(const int report_type, void * const return_address, const wchar_t * const file_name, const wchar_t * const line_number, const wchar_t * const module_name, const wchar_t * const user_message) Line 452	C++
 	ucrtbased.dll!_VCrtDbgReportW(int nRptType, void * returnAddress, const wchar_t * szFile, int nLine, const wchar_t * szModule, const wchar_t * szFormat, char * arglist) Line 642	C++
 	ucrtbased.dll!_CrtDbgReportW(int report_type, const wchar_t * file_name, int line_number, const wchar_t * module_name, const wchar_t * format, ...) Line 273	C++
 	ucrtbased.dll!issue_debug_notification(const wchar_t * const message) Line 122	C++
 	ucrtbased.dll!__acrt_report_runtime_error(const wchar_t * message) Line 142	C++
 	ucrtbased.dll!abort() Line 61	C++
 	ni_grpc_device_server.exe!grpc::CoreCodegen::assert_fail(const char * failed_assertion, const char * file, int line) Line 246	C++
 	ni_grpc_device_server.exe!grpc::internal::CallbackWithSuccessTag::Set(grpc_call * call, std::function<void __cdecl(bool)> f, grpc::internal::CompletionQueueTag * ops, bool can_inline) Line 164	C++
>	ni_grpc_device_server.exe!grpc::internal::CallbackServerStreamingHandler<nidaqmx_grpc::RegisterDoneEventRequest,nidaqmx_grpc::RegisterDoneEventResponse>::ServerCallbackWriterImpl::Finish(grpc::Status s) Line 523	C++
 	ni_grpc_device_server.exe!grpc::ServerWriteReactor<nidaqmx_grpc::RegisterDoneEventResponse>::Finish(grpc::Status s) Line 648	C++
 	ni_grpc_device_server.exe!nidevice_grpc::ServerWriterReactor<nidaqmx_grpc::RegisterDoneEventResponse,nidevice_grpc::CallbackRegistration>::OnCancel() Line 43	C++
 	ni_grpc_device_server.exe!<lambda_2f27ce0846995826ab9faa5139791063>::<lambda_invoker_cdecl>(void * void_arg, absl::lts_20220623::Status __formal) Line 70	C++
 	ni_grpc_device_server.exe!grpc_core::Executor::RunClosures(const char * executor_name, grpc_closure_list list) Line 127	C++
 	ni_grpc_device_server.exe!grpc_core::Executor::ThreadMain(void * arg) Line 245	C++
 	ni_grpc_device_server.exe!`anonymous namespace'::ThreadInternalsWindows::thread_body(void * v) Line 122	C++
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown
```

I think the problem is that we are calling `Finish()` twice:
- In the `RegisterXEventReactor` constructor because `start()` returned a not-ok status. 
- Again in `ServerWriteReactor<TResponse>::OnCancel()`

Calling `Finish()` sets `ServerCallbackWriterImpl::finish_tag_`, which can only be done once.

`grpcpp/support/server_callback.h` doesn't say to call `Finish()` "exactly once", but [grpcpp/support/async_stream.h](https://github.com/grpc/grpc/blob/0526a51734003180862331e2527503a5d1898c95/include/grpcpp/support/async_stream.h#L51) and [grpcpp/support/sync_stream.h](https://github.com/grpc/grpc/blob/0526a51734003180862331e2527503a5d1898c95/include/grpcpp/support/sync_stream.h#L39) do.

Comment (bkeryan) [reply generated/nidaqmx/nidaqmx_service.cpp:14009]: I wonder why the system tests didn't catch this.

File: source/tests/system/nidaqmx_driver_api_tests.cpp [hunk 3]
```diff
@@ -1439,10 +1477,109 @@ TEST_F(NiDAQmxDriverApiTests, ChannelWithDoneEventRegisteredTwice_RunCompleteFin
...
+  ASSERT_EQ(Completion(FINISH_TAG, true), get_next_completion(cq));
+  EXPECT_THROW({
+    try {
+      client::raise_if_error(status, reader_context);
+    }
+    catch (const client::grpc_driver_error& ex) {
+      expect_driver_error(ex, EVERY_N_SAMPS_TRANSFERRED_FROM_BUFFER_EVENT_NOT_SUPPORTED_BY_DEVICE_ERROR);
+      throw;
+    }
+  }, client::grpc_driver_error);
```
Comment (bkeryan) [inline source/tests/system/nidaqmx_driver_api_tests.cpp:1582]: FYI, I want to try cleaning up these `EXPECT_THROW` blocks by extracting an `EXPECT_THROW_GRPC_DRIVER_ERROR` macro. I'll post a separate PR.

File: generated/nifake_non_ivi/nifake_non_ivi_service.cpp [hunk 4]
```diff
@@ -790,19 +790,17 @@ namespace nifake_non_ivi_grpc {
             return 0;
         });
 
+        const auto& session_repository_ = service->session_repository_;
         myInt16 input_data = request->input_data();
 
         auto status = library->RegisterCallback(input_data, CallbackRouter::handle_callback, handler->token());
+        if (!status_ok(status)) {
+          return service->ConvertApiErrorStatusForFakeHandle(context, status, 0);
+        }
```
Comment (bkeryan) [inline generated/nifake_non_ivi/nifake_non_ivi_service.cpp:799]: TODO: add at least one integration test for stream errors

**Review by astarche — APPROVED** [review]

**Review by astarche — APPROVED** [review]

**Review by reckenro — APPROVED** [review]

File: generated/nidaqmx/nidaqmx_service.cpp (hunk 2 above)
Comment (bkeryan) [reply generated/nidaqmx/nidaqmx_service.cpp]: Fixed by adding `bool ServerWriteReactor::try_finish(::grpc::Status)`, which only calls `Finish()` once.

**Review by reckenro — APPROVED** [review]

File: source/tests/system/nidaqmx_driver_api_tests.cpp (hunk 3 above)
Comment (bkeryan) [reply source/tests/system/nidaqmx_driver_api_tests.cpp:1652]: https://github.com/ni/grpc-device/pull/933

File: source/tests/system/nidaqmx_driver_api_tests.cpp [hunk 5]
```diff
@@ -1439,10 +1478,178 @@ TEST_F(NiDAQmxDriverApiTests, ChannelWithDoneEventRegisteredTwice_RunCompleteFin
...
+{
+  const auto N_SAMPLES = 10UL;
+  const auto N_READS = 10UL;
+  const auto EVENT_START_CALL_TAG = (void*)1;
+  const auto EVENT_READ_INITIAL_METADATA_TAG = (void*)2;
+  const auto EVENT_READ_TAG = (void*)3;
+  const auto READ_ANALOG_F64_TAG = (void*)4;
+  create_ai_voltage_chan(0.0, 1.0);
+  ::grpc::ClientContext event_context;
+  ::grpc::CompletionQueue completion_queue;
```
Comment (bkeryan) [inline source/tests/system/nidaqmx_driver_api_tests.cpp:1552]: While writing the register/unregister tests, I found that if the test function returns or throws while there are pending async operations, it may corrupt the stack. These tests should shut down the completion queue on exit to ensure that it has no dangling references to stack variables.

Comment (bkeryan) [reply source/tests/system/nidaqmx_driver_api_tests.cpp:1553]: Fixed by using RAII to shut down the completion queue:
```
auto shut_down_on_exit = make_scope_exit([&]{ shut_down_completion_queue(completion_queue); });
```

**Review by astarche — APPROVED** [review]

File: source/tests/system/nidaqmx_driver_api_tests.cpp [hunk 6]
```diff
@@ -1439,10 +1479,180 @@ TEST_F(NiDAQmxDriverApiTests, ChannelWithDoneEventRegisteredTwice_RunCompleteFin
...
+{
+  const auto N_SAMPLES = 10UL;
+  create_ai_voltage_chan(0.0, 1.0);
+  ::grpc::ClientContext reader_context;
+  auto reader = register_every_n_samples_event(reader_context, N_SAMPLES, EveryNSamplesEventType::EVERY_N_SAMPLES_EVENT_TYPE_TRANSFERRED_FROM_BUFFER);
+
+  reader_context.TryCancel();
+}
+
+TEST_F(NiDAQmxDriverApiTests, AsyncEveryNSamplesEventRegistered_OnEventReadAnalogF64_EventAndReadResponsesAreReceived)
```
Comment (bkeryan) [inline source/tests/system/nidaqmx_driver_api_tests.cpp:1543]:
```
[ RUN      ] NiDAQmxDriverApiTests.AsyncEveryNSamplesEventRegistered_OnEventReadAnalogF64_EventAndReadResponsesAreReceived
/opt/actions-runner/_work/_temp/8[92](https://github.com/ni/grpc-device/actions/runs/5047577024/jobs/9064618937#step:5:93)d9ccb-3fdf-43e6-b8c3-b413564be71f.sh: line 1:  3144 Segmentation fault      (core dumped) ./SystemTestsRunner --gtest_filter=-NiRFSA*:NiRFSG*:NiDCPower*CalSelfCalibrate*
Error: Process completed with exit code 139.
```

Comment (bkeryan) [reply source/tests/system/nidaqmx_driver_api_tests.cpp:1543]: I set up a Linux VM to debug this, and the main branch crashes without the change from this PR: https://github.com/ni/grpc-device/issues/936

Comment (bkeryan) [reply source/tests/system/nidaqmx_driver_api_tests.cpp:1543]: With the `make_scope_exit` fix, both `run_win_system_tests` and `run_linux_system_tests` are now passing.
